[package]
name = "dibsv3"
version = "0.0.1"
authors = ["Nate Tenczar <ntenczar@gmail.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
cargo-watch = "6.0.0"
